name: Build test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run composite action
        uses: uros-simeunovic/workflows/.github/core-action@main