name: Build test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: uros-simeunovic/workflows
          path: repo-workflows
      
      - name: Show files
        shell: bash
        run: ls -la repo-workflows/scripts

      - name: Run composite action
        uses: uros-simeunovic/workflows/.github/core-action@main