name: Build test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Show files
        shell: bash
        run: ls -la

      - name: Run composite action
        uses: uros-simeunovic/workflows/.github/core-action@main