name: Reusable Workflow

on:
  workflow_call:

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Call Composite Action
        uses: uros-simeunovic/workflows/.github/core-action@main